package com.crawdwall_backend_api.company;

public enum CompanyKycTwoStep {
    BANKING_AND_FINANCIAL_ACCOUNTS,
    AUTHORIZED_SIGNATORIES_AND_CONTROL,
    FINANCIAL_INTEGRITY_AND_RISK_CONTROLS,
    EXECUTION_AND_REPORTING_READINESS,
    CAPITAL_GOVERNANCE_AGREEMENT,
    KYC_COMPLETED
}